server:
  port: 9003
  

#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis所在路径
#  type-aliases-package: com.vo #entity别名类
#  mapper-locations:
#  - classpath:mybatis/mapper/**/*.xml #mapper映射文件
  
#服务名称  
spring: 
  application: 
    name: eureka-dept-zuul
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: qk941009
#    dbcp2:
#      min-idle: 5
#      initial-size: 5
#      max-total: 5
#      max-wait-millis: 200
         
eureka: 
  instance:
      hostname: localhost
      prefer-ip-address: true
      instance-id: gateway-9527.com
  client:
    service-url: 
      defaultZone: http://localhost:8762/eureka/
      
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul: 
#  ignored-services: EUREKA-CLIENT
#  我们可以指定一个全局的前缀
  prefix: /com
#   忽略所有请求
  ignored-services: "*"
  routes: 
#    simpleRouter: 
#      path: simpleRouter//wangyi
#      url: http://localhost:8092/
#    ##简单路由其实可以省略path
#    simple163: 
#      url: http://localhost:8092/
#  就是把 /mydept代替EUREKA-CLIENT 使用，相当于起了一个别名, 直接访问 http://localhost:9003/com/mydept/dept/get/3
    mydept.serviceId: EUREKA-CLIENT
    mydept.path: /mydept/**
 
#启用Feign对Hystrix的支持
#feign: 
#  hystrix: 
#   enabled: true
   